// Generates worker/seed.sql from src/data/titles.js so the database and the
// frontend stay in sync. Run: node scripts/generate-seed.mjs
import { writeFileSync } from 'node:fs';
import { titles, featured } from '../src/data/titles.js';

const esc = (v) => {
  if (v === null || v === undefined) return 'NULL';
  return `'${String(v).replace(/'/g, "''")}'`;
};

const rows = titles.map((t, i) => {
  const id = `seed-${String(i + 1).padStart(3, '0')}`;
  return `(
  ${esc(id)},
  ${esc(t.id)},
  ${esc(t.type)},
  ${esc(t.title)},
  ${esc(t.synopsis)},
  ${esc(JSON.stringify(t.genres))},
  ${esc(t.releaseDate)},
  ${esc(t.runtime)},
  ${Number(t.rating)},
  ${esc(t.posterUrl)},
  ${esc(t.backdropUrl)},
  ${esc(t.videoUrl)},
  ${esc(t.subtitlesUrl)},
  ${t.id === featured.id ? 1 : 0}
)`;
});

const sql = `-- Generated by scripts/generate-seed.mjs - do not edit by hand.
-- Placeholder catalog so early testers have something to browse.

INSERT OR REPLACE INTO titles
  (id, slug, type, title, synopsis, genres, release_date, runtime, rating,
   poster_url, backdrop_url, video_url, subtitles_url, featured)
VALUES
${rows.join(',\n')};

-- Give the flagship series one season of episodes so the detail page has a rail.
INSERT OR REPLACE INTO seasons (id, title_id, season_number, description) VALUES
  ('seed-s1', 'seed-001', 1, 'First season of Solaris Requiem.');

INSERT OR REPLACE INTO episodes
  (id, season_id, episode_number, title, video_manifest_url, subtitles_url, runtime)
VALUES
  ('seed-e1', 'seed-s1', 1, 'The Listening Station',
   'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8', '/subtitles/sample.vtt', '10:34'),
  ('seed-e2', 'seed-s1', 2, 'Salvage Rights',
   'https://test-streams.mux.dev/test_001/stream.m3u8', '/subtitles/sample.vtt', '09:58');
`;

writeFileSync(new URL('../worker/seed.sql', import.meta.url), sql, 'utf8');
console.log(`wrote worker/seed.sql with ${titles.length} titles`);