// Generates worker/seed.sql from src/data/titles.js so the database and the
// frontend stay in sync. Run: node scripts/generate-seed.mjs
import { writeFileSync } from 'node:fs';
import { titles, featured } from '../src/data/titles.js';

// Types that ship as episodes. Mirrors EPISODIC_TYPES in worker/api.js and
// isEpisodic() in src/lib/titleTypes.js.
const EPISODIC = new Set(['series', 'anime', 'ai']);

const HLS_SAMPLES = [
  'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  'https://test-streams.mux.dev/test_001/stream.m3u8',
];

const esc = (v) => {
  if (v === null || v === undefined) return 'NULL';
  return `'${String(v).replace(/'/g, "''")}'`;
};

/** Stable synthetic id for a title's DB row, based on its position. */
const titleId = (index) => `seed-${String(index + 1).padStart(3, '0')}`;

const rows = titles.map((t, i) => {
  const id = titleId(i);
  return `(
  ${esc(id)},
  ${esc(t.id)},
  ${esc(t.type)},
  ${esc(t.title)},
  ${esc(t.synopsis)},
  ${esc(JSON.stringify(t.genres))},
  ${esc(t.releaseDate)},
  ${esc(t.runtime)},
  ${Number(t.rating)},
  ${esc(t.posterUrl)},
  ${esc(t.backdropUrl)},
  ${esc(t.videoUrl)},
  ${esc(t.subtitlesUrl)},
  ${t.id === featured.id ? 1 : 0}
)`;
});

// Seasons and episodes, derived from each title's own `seasons` array.
// Previously this was hardcoded to the flagship series, which left every other
// series and anime with an empty episode list.
const seasonRows = [];
const episodeRows = [];

titles.forEach((t, i) => {
  if (!EPISODIC.has(t.type) || !t.seasons?.length) return;

  const parent = titleId(i);
  t.seasons.forEach((season, sIndex) => {
    const seasonId = `${parent}-s${sIndex + 1}`;
    seasonRows.push(
      `  (${esc(seasonId)}, ${esc(parent)}, ${sIndex + 1}, ${esc(season.description ?? null)})`,
    );

    (season.episodes || []).forEach((ep, eIndex) => {
      // Alternate the public test streams so episodes are not all identical.
      const stream = HLS_SAMPLES[(i + eIndex) % HLS_SAMPLES.length];
      episodeRows.push(
        `  (${esc(`${seasonId}-e${eIndex + 1}`)}, ${esc(seasonId)}, ${eIndex + 1}, ${esc(ep.title)}, ` +
          `${esc(stream)}, ${esc(t.subtitlesUrl)}, ${esc(ep.runtime ?? null)})`,
      );
    });
  });
});

const sections = [`-- Generated by scripts/generate-seed.mjs - do not edit by hand.
-- Placeholder catalog so early testers have something to browse.
-- Playback for series/anime/ai needs a signed-in account; see EPISODIC_TYPES.

INSERT OR REPLACE INTO titles
  (id, slug, type, title, synopsis, genres, release_date, runtime, rating,
   poster_url, backdrop_url, video_url, subtitles_url, featured)
VALUES
${rows.join(',\n')};`];

if (seasonRows.length) {
  sections.push(`INSERT OR REPLACE INTO seasons (id, title_id, season_number, description) VALUES
${seasonRows.join(',\n')};`);
}

if (episodeRows.length) {
  sections.push(`INSERT OR REPLACE INTO episodes
  (id, season_id, episode_number, title, video_manifest_url, subtitles_url, runtime)
VALUES
${episodeRows.join(',\n')};`);
}

writeFileSync(new URL('../worker/seed.sql', import.meta.url), `${sections.join('\n\n')}\n`, 'utf8');

console.log(
  `wrote worker/seed.sql: ${titles.length} titles, ${seasonRows.length} seasons, ${episodeRows.length} episodes`,
);